--- #YAML:1.0
name:                Catalyst-Authentication-AuthTkt
version:             0.05
abstract:            shim for Apache::AuthTkt
license:             ~
author:              
    - Peter Karman <karman at cpan dot org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache::AuthTkt:               0.08
    Catalyst:                      5.7014
    Catalyst::Plugin::Authentication: 0.10007
    Catalyst::Plugin::Static::Simple: 0
    Config::General:               0
    Data::Dump:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
