--- #YAML:1.0
name:               Catalyst-Authentication-AuthTkt
version:            0.12
abstract:           shim for Apache::AuthTkt
author:
    - Peter Karman <karman at cpan dot org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache::AuthTkt:      0.08
    Catalyst:             5.7014
    Catalyst::Plugin::Authentication:  0.10007
    Catalyst::Plugin::ConfigLoader:  0
    Catalyst::Plugin::Session:  0
    Catalyst::Plugin::Session::State::Cookie:  0
    Catalyst::Plugin::Session::Store::Dummy:  0
    Catalyst::Plugin::Static::Simple:  0
    Config::General:      0
    Data::Dump:           0
    Moose:                0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
