---
abstract: 'shim for Apache::AuthTkt'
author:
  - 'Peter Karman <karman at cpan dot org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-AuthTkt
no_index:
  directory:
    - t
    - inc
requires:
  Apache::AuthTkt: 0.08
  Catalyst: 5.7014
  Catalyst::Plugin::Authentication: 0.10007
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::Dummy: 0
  Catalyst::Plugin::Static::Simple: 0
  Config::General: 0
  Data::Dump: 0
  Moose: 0
  Test::More: 0
version: 0.14
